version: "3"

services:

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  rabbit-receiver:
    image: rabbit-receiver
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    depends_on:
      - rabbitmq